### ISSUE TITLE
[Feature Request] Support for M1 Macs

### ISSUE THREAD

**Issue by lucastrvsn** [qmk/homebrew-qmk#12]
Hello! I'm unable to use qmk cli on my m1 macbook. Can this be upgrade to support m1 macs?

**Comment by skullydazed** [comment]
This is not something within our power to do at this time. We have to wait for many upstream tools, including gcc. Your best bet for now is to follow this workaround: https://github.com/osx-cross/homebrew-avr/issues/220#issuecomment-777649776

We'll leave this open for now so others can find this solution.

**Comment by mguterl** [comment]
@skullydazed @drashna I believe this can be closed now. I was able to install QMK with my ARM homebrew and it compiled my firmware without issues.

The formula for `avr-gcc@8` is "keg-only" and you must manually add avr-gcc to your PATH: `export PATH="/opt/homebrew/opt/avr-gcc@8/bin:$PATH"`.

**Comment by fauxpark** [comment]
The install process should do that automatically: https://github.com/qmk/qmk_firmware/blob/master/util/install/macos.sh#L22

**Comment by mguterl** [comment]
> The install process should do that automatically: https://github.com/qmk/qmk_firmware/blob/master/util/install/macos.sh#L22

Thanks, I undid my PATH changes, ran `qmk setup`, and this works! I forgot to run `qmk setup` again after installing the package with my ARM homebrew.
