### ISSUE TITLE
[Bug] 404 error stops install for qmk-0.3.0.catalina.bottle.targ.gz

### ISSUE THREAD

**Issue by rfreedman5280** [qmk/homebrew-qmk#30]
### Describe the Bug

The install goes great until this comes back:

Downloading https://github.com/qmk/homebrew-qmk/releases/download/qmk-0.3.0/
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "qmk"
Download failed: https://github.com/qmk/homebrew-qmk/releases/download/qmk-0.3.0/qmk-0.3.3.catalina.bottle.tar.gz

I tried to download the file myself and drop it into the homebrew folder that everything else was going to, but it still didn't work.

### Additional Context?

Installing on OS Big Sur from freshly updated Homebrew

**Comment by fauxpark** [comment]
The bottle wasn't built for 0.3.3, the PR wasn't merged correctly: #28
There should be a new CLI release soon anyway, so we will probably skip over this.

**Comment by rfreedman5280** [comment]
> The bottle wasn't built for 0.3.3, the PR wasn't merged correctly: #28
> There should be a new CLI release soon anyway, so we will probably skip over this.

I'm new to coding, s I'm not quite sure how all this works. Does that mean I can just wait a while and try again? Thanks for your help, and thanks in advance for your patience with my lack of coding experience.

**Comment by fauxpark** [comment]
Should be fixed as of #32.
