### ISSUE TITLE
[Bug] Cannot Install QMK on M1 Mac, Even with Homebrew, Identical result using Rosetta 2

### ISSUE THREAD

**Issue by BLTHSHZZR** [qmk/homebrew-qmk#44]
### I have installed Homebrew. When I attempt to use the command "brew install qmk/qmk/qmk" this is the result (note that this has been repeatedly attempted, hence the "already installed" line items. I have also attempt this same process using Rosetta (install homebrew with Rosetta and then attempt to install the CLI) with the same result. 

This is the whole log, any help is greatly appreciated. 

Last login: Sat Sep 10 20:35:01 on ttys000
UserName@Users-Mac-mini ~ % brew install qmk/qmk/qmk
==> Downloading https://files.pythonhosted.org/packages/d7/d8/05696357e0311f5b5c
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/d46628d315f103ea527907020cf5f6c94365bbb549783f75a794526482afb672--appdirs-1.4.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/05/f8/67851ae4fe5396ba68
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/d80b401c80fa060d397ef1e894495831c216b23802b5943dfd8ac212e3e31f6f--argcomplete-2.0.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/1a/cb/c4ffeb41e7137b2375
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/8108507f92eecf1db105ec3399ff5b1c928af0968c17e2c9f6fc4b8ab7c1801f--attrs-22.1.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/2b/65/24d033a9325ce42ccb
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/cd3c0455424aa953b463cc8c3e88bda00024799daba38cc4ccea21c114aa5158--colorama-0.4.5.tar.gz
==> Downloading https://files.pythonhosted.org/packages/6a/ab/88d67f02024700b48c
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/f1545a11fd229c96a9d0f72b7028be9698be626008009829b9fdea774f414101--dotty_dict-1.3.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ee/48/d53580d30b1fabf25d
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/4727d0b748b50e2e4f5fc42c047873878b3acf304a09b3b89d933855dd178535--halo-0.0.31.tar.gz
==> Downloading https://files.pythonhosted.org/packages/e0/2a/87d8d87343c9be4f83
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/5f08cde856aeda7005a327dd63dadc71658841bb4ebb1a42f7dc372c8783e653--hid-1.0.5.tar.gz
==> Downloading https://files.pythonhosted.org/packages/82/e5/0b56d723a76ca67aba
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/8acb1b2658a24095b64da16979200ec54f83525a38700902cc6f125b05d70371--hjson-3.1.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fb/f3/44393ff5be9008b922
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/5251ccdd36fae541cc4d2fc83394cb79e492846ef1ba9a484203d30434034cf3--jsonschema-4.13.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/45/87/e86645d758a4401c8c
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/cb11b132d31dbe503e62ecf5e3c89fc1f33e804b9e3920826bb28e0fa94d300b--log_symbols-0.0.14.tar.gz
==> Downloading https://files.pythonhosted.org/packages/92/c0/3377091d68d98f7448
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/4eae820ef084c651ba53c34792df6f4889cfef58879cf2b41f626a76b7693f8d--milc-1.6.6.tar.gz
==> Downloading https://files.pythonhosted.org/packages/8c/92/2975b464d9926dc667
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/bc794bd01f698c8c5f21e3dc88b94aff82b239596e0bbdcf7f157c74dc329c3c--Pillow-9.2.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/e0/ef/5905cd3642f2337d44
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/9fa20b611f82473c8c9d488adcec4b4c581c79c54080d8a46b2979a67720868b--Pygments-2.13.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/42/ac/455fdc7294acc4d415
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/dc555fdd34304dbbde680a019283ec640b66188e51afe042e85db9a6a2075a39--pyrsistent-0.18.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/1e/7d/ae3f0a63f41e4d2f6c
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/9539dfa1f22434f69c7dc3a036dd8901eab0d487816cb11aa706e220b6d967ca--pyserial-3.5.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d9/6e/433a5614132576289b
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/e34b8c197df27ea358bb20b554183616eb7d38ee383c4f254133e71f8370816b--pyusb-1.2.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/71/39/171f1c67cd00715f19
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/3090f0022e8388f5c3bbff25d19f54b7af62562659cbf599e5f7fb044f280199--six-1.16.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d3/91/bb331f0a43e04d950a
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/97375e1304f55f3a8697849128ced63c797b28555b69ee9528d20fc9034097d2--spinners-0.0.24.tar.gz
==> Downloading https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/2f663a83eb738377295cb9dece37a7fa4dea54dbfb7b86bcacf96bc2035bc58d--termcolor-1.1.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/52/4a/27caeef7f15316271a
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/776e677253669e66640dff7c339bafea6566673f9d7565a6bb05bc00fedd3e96--qmk-1.1.1.tar.gz
==> Installing qmk from qmk/qmk
==> python3 -m venv --system-site-packages /opt/homebrew/Cellar/qmk/1.1.1/libexec
==> /opt/homebrew/Cellar/qmk/1.1.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/qmk--appdirs-20220911-38195
==> /opt/homebrew/Cellar/qmk/1.1.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/qmk--argcomplete-20220911-3
==> /opt/homebrew/Cellar/qmk/1.1.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/qmk--attrs-20220911-38195-j
==> /opt/homebrew/Cellar/qmk/1.1.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/qmk--colorama-20220911-3819
==> /opt/homebrew/Cellar/qmk/1.1.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/qmk--dotty-dict-20220911-38
==> /opt/homebrew/Cellar/qmk/1.1.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/qmk--halo-20220911-38195-jr
==> /opt/homebrew/Cellar/qmk/1.1.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/qmk--hid-20220911-38195-uvd
==> /opt/homebrew/Cellar/qmk/1.1.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/qmk--hjson-20220911-38195-j
==> /opt/homebrew/Cellar/qmk/1.1.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/qmk--jsonschema-20220911-38
Last 15 lines from /Users/UserName/Library/Logs/Homebrew/qmk/10.pip:
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/homebrew/Cellar/qmk/1.1.1/libexec/bin/python3.10 /opt/homebrew/Cellar/qmk/1.1.1/libexec/lib/python3.10/site-packages/pip/__pip-runner__.py install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-7mbpp4of/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- hatchling hatch-vcs hatch-fancy-pypi-readme
  cwd: [inherit]
  Installing build dependencies: finished with status 'error'
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Do not report this issue to Homebrew/brew or Homebrew/core!

UserName@Users-Mac-mini ~ %

**Comment by fauxpark** [comment]
You need to install Homebrew itself under Rosetta 2, and install the CLI through that.

**Comment by BLTHSHZZR** [comment]
> You need to install Homebrew itself under Rosetta 2, and install the CLI through that.

I have attempted this already with the same result. However, do I need to uninstall Homebrew first before installing it with Rosetta?

**Comment by fauxpark** [comment]
Did you follow this guide? https://www.reddit.com/r/olkb/comments/nh2fk9/guide_installing_qmk_on_m1_macbook/

**Comment by BLTHSHZZR** [comment]
> Did you follow this guide? https://www.reddit.com/r/olkb/comments/nh2fk9/guide_installing_qmk_on_m1_macbook/

Thank you, that seems to have worked to install qmk (I assume all qmk commands will have to be run through the rosetta terminal?)

 however I'm now having this issue when I try to run "qmk compile"

> user@users-Mac-mini ~ % qmk compile
☒ Could not determine keyboard!
☒ You must supply a configurator export, both `--keyboard` and `--keymap`, or be in a directory for a keyboard or keymap.
usage: qmk compile [-h] [-b] [-kb KEYBOARD] [-km KEYMAP] [filename]
user@users-Mac-mini ~ %

**Comment by fauxpark** [comment]
Have you read what the error message says? That's what it's there for.

**Comment by BLTHSHZZR** [comment]
> https://www.reddit.com/r/olkb/comments/nh2fk9/guide_installing_qmk_on_m1_macbook/

I'm working through it. At this point I have QMK installed and that's further than I've gotten on this project before SO thank you and I hope this issue helps someone else in the future.

**Comment by sbmueller** [comment]
I could resolve this with
```
pip3 install --upgrade pathspec
```
