### ISSUE TITLE
Error "Bad Interpreter" on Mac OS [Bug] 

### ISSUE THREAD

**Issue by android606** [qmk/homebrew-qmk#48]
### Describe the Bug

1. Start with a Mac that does not have python 3.10 installed
2. install using `homebrew qmk/qmk/qmk`
3. run `qmk setup`

Error message appears:
`/usr/local/bin/qmk: bad interpreter: /usr/local/Cellar/qmk/1.1.1/libexec/bin/python3.10: no such file or directory`

### Additional Context?

**Notes**
- 'python' is listed as a dependency for qmk, and it currently installs python 3.11
- symlink `/usr/local/Cellar/qmk/1.1.1/libexec/bin/python3.10` exists, and points to `../../../../../opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin/python3.10`
- symlink target does not exist

**Reference**
I believe fixing this will fix qmk/qmk_firmware#19882

**Workaround**
Manually installing python 3.10 with `brew install python@3.10` works around this issue.

Thanks for the useful project!

**Comment by android606** [comment]
`brew install --rebuild-from-source qmk/qmk/qmk` also works.

**Comment by fauxpark** [comment]
I've updated the formula, please try it now.

**Comment by android606** [comment]
Yep, that fixed it.  Thanks!
