### ISSUE TITLE
[Feature Request] Update caveats to help users configure PATH for arm-none-eabi-gcc and avr-gcc

### ISSUE THREAD

**Issue by cskeeters** [qmk/homebrew-qmk#54]
### Description

When I install qmk with brew, it installs the packages **avr-gcc@8** and **arm-gcc-bin@8**.  As a result, the executables `arm-none-eabi-gcc` and `avr-gcc` are installed, but those packages don't link those executables to `/opt/homebrew/bin` (prefix may vary).  Since they were not linked to a folder I already have in my path, `qmk setup` asks if I want to install them.

*NOTE: I'm running an M1 Macbook Pro.  I'm not sure how the architecture affects the final config.*

Would it be a good idea to update the caveats to let the user know that the required binaries may not be linked and to suggest that they run the following and update their paths?

    brew link avr-gcc@8
    brew link arm-gcc-bin@8

When I do this, it tells me exactly what to add to `.bashrc`.

```
Warning: avr-gcc@8 is keg-only and must be linked with `--force`.

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/opt/homebrew/opt/avr-gcc@8/bin:$PATH"' >> /Users/chad/.bash_profile
```

```
Warning: arm-gcc-bin@8 is keg-only and must be linked with `--force`.

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/opt/homebrew/opt/arm-gcc-bin@8/bin:$PATH"' >> /Users/chad/.bash_profile
```

**Comment by fauxpark** [comment]
The AVR and ARM toolchains will be linked in the course of `qmk setup`. There is no need to add caveats as there isn't much the CLI can do without setting up the qmk_firmware repo.

**Comment by cskeeters** [comment]
In my case, I had a forked qmk_firmware repo that I copied over from another machine.  The code for my new keyboard hasn't been merged into qmk_firmware yet.  I used `brew install qmk/qmk/qmk` as the [instructions say](https://docs.qmk.fm/#/newbs_getting_started).  When qmk compile didn't work, I did run `qmk doctor` which asked me if I wanted to install software for arm-none-eabi-gcc and avr-gcc and I thought "No, I already have them installed!  Don't install more stuff in a way I might have to clean up later".  After tracing the code, I see now that `qmk doctor` will eventually [force link these packages with brew](https://github.com/qmk/qmk_firmware/blob/d6ce42ae5b1093eeae215c073c733c800195ec28/util/install/macos.sh#L22) and does not install packages that are already installed.

Now that I know how it works and that qmk doctor will use brew I think you are correct that you can depend on `qmk setup` or `qmk doctor` being run to finish setting up the computer for use.  I will close this issue.

I commend everyone who has worked together to make this work and pretty well at that.  Especially for those new to development.
