### ISSUE TITLE
ERROR: Could not build wheels for pillow, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by adrnlow** [qmk/homebrew-qmk#75]
### Describe the Bug

i'm trying to install qmk without success. Have been encountering various errors; with the most recent error being above. i'm not sure what it is and will appreciate some help in setting up QMK. Thanks.
i've appended the log below.

### Additional Context?

Last login: Thu Feb 29 17:18:40 on ttys000
adrnlow@Adrians-MacBook-Pro-2 ~ % brew list
==> Formulae
aom			jpeg-turbo		mpdecimal
arm-none-eabi-binutils	lame			mpfr
arm-none-eabi-gcc@8	leptonica		nettle
asdf			libass			opencore-amr
autoconf		libbluray		openjpeg
automake		libevent		openssl
avr-binutils		libffi			openssl@3
avr-gcc@8		libftdi			opus
avrdude			libimagequant		p11-kit
boost			libmpc			pcre
bootloadhid		libogg			pcre2
ca-certificates		libpng			pillow
cairo			libraqm			pixman
clang-format		libsamplerate		python
confuse			libsndfile		python@3.12
coreutils		libsoxr			qmk
dfu-programmer		libtasn1		readline
dfu-util		libtiff			rtmpdump
ffmpeg			libtool			rubberband
flac			libunistring		sdl2
fontconfig		libusb			snappy
freetype		libusb-compat		speex
frei0r			libvorbis		sqlite
fribidi			libvpx			tcl-tk
gdbm			libx11			teensy_loader_cli
gettext			libxau			tesseract
giflib			libxcb			theora
glib			libxdmcp		unbound
gmp			libxext			unixodbc
gnutls			libxrender		webp
graphite2		libyaml			x264
harfbuzz		little-cms2		x265
hid_bootloader_cli	lz4			xorgproto
hidapi			lzo			xvid
icu4c			m4			xz
isl			make			zstd
jpeg			mdloader

adrnlow@Adrians-MacBook-Pro-2 ~ % asdf list ruby
  3.3.0
adrnlow@Adrians-MacBook-Pro-2 ~ % qmk setup
zsh: /usr/local/bin/qmk: bad interpreter: @@HOMEBREW_CELLAR@@/qmk/1.1.2_4/libexec/bin/python: no such file or directory
adrnlow@Adrians-MacBook-Pro-2 ~ % brew doctor
Your system is ready to brew.
adrnlow@Adrians-MacBook-Pro-2 ~ % brew update
Already up-to-date.
adrnlow@Adrians-MacBook-Pro-2 ~ % brew install qmk/qmk/qmk
qmk 1.1.2_4 is already installed but outdated (so it will be upgraded).
==> Downloading https://ghcr.io/v2/qmk/qmk/qmk/manifests/1.1.5
curl: (22) The requested URL returned error: 404

==> Fetching qmk/qmk/qmk
==> Downloading https://ghcr.io/v2/qmk/qmk/qmk/blobs/sha256:3e6280308efd18258c31287023d4c7e72003028f7efd2d8e01ef266a5103d2d8
Already downloaded: /Users/adrnlow/Library/Caches/Homebrew/downloads/27aa0783b1ef2085def30fff70fdbc3f0b9df4b4cc23d82a865ead0ef87c6bb2--qmk--1.1.5.ventura.bottle.tar.gz
==> Upgrading qmk/qmk/qmk
  1.1.2_4 -> 1.1.5 

==> Pouring qmk--1.1.5.ventura.bottle.tar.gz
Error: /usr/local/Cellar/qmk/1.1.5 is not a directory
adrnlow@Adrians-MacBook-Pro-2 ~ % qmk upgrade
zsh: /usr/local/bin/qmk: bad interpreter: @@HOMEBREW_CELLAR@@/qmk/1.1.2_4/libexec/bin/python: no such file or directory
adrnlow@Adrians-MacBook-Pro-2 ~ % brew update qmk
Error: This command updates brew itself, and does not take formula names.
Use `brew upgrade qmk` instead.
adrnlow@Adrians-MacBook-Pro-2 ~ % brew upgrade qmk
==> Upgrading 1 outdated package:
qmk/qmk/qmk 1.1.2_4 -> 1.1.5
==> Fetching qmk/qmk/qmk
==> Downloading https://files.pythonhosted.org/packages/d7/d8/05696357e0311f5b5c316d7b95f46c669dd9c15aaeecbb48c7d0aeb88c40/appdir
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/f0/a2/ce706abe166457d5ef68fac3ffa6cf0f93580755b7d5f883c456e94fab7b/argcom
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/e3/fc/f800d51204003fa8ae392c4e8278f256206e7a919b708eef054f5f4b650d/attrs-
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/d8/53/6f443c9a4a8358a93a6792e2acffb9d9d5cb0a5cfd8802644b7b1c9a02e4/colora
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/6a/ab/88d67f02024700b48cd8232579ad1316aa9df2272c63049c27cc094229d6/dotty_
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/ee/48/d53580d30b1fabf25d0d1fcc3f5b26d08d2ac75a1890ff6d262f9f027436/halo-0
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/50/b8/5f470948262b6cdda8e1b2382b19f67c57eacda1e07a14322807b911e0ce/hid-1.
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/82/e5/0b56d723a76ca67abadbf7fb71609fb0ea7e6926e94fcca6c65a85b36a0e/hjson-
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/36/3d/ca032d5ac064dff543aa13c984737795ac81abc9fb130cd2fcff17cfabc7/jsonsc
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/45/87/e86645d758a4401c8c81914b6a88470634d1785c9ad09823fa4a1bd89250/log_sy
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/3c/7f/f13f3cbdbc0284440cee8a3a4a0aeccde2f99c51f6c1f81f3a5bc033f11e/milc-1
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/f8/3e/32cbd0129a28686621434cbf17bb64bf1458bfb838f1f668262fefce145c/pillow
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/55/59/8bccf4157baf25e4aa5a0bb7fa3ba8600907de105ebc22b0c78cfbf6f565/pygmen
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/ce/3a/5031723c09068e9c8c2f0bc25c3a9245f2b1d1aea8396c787a408f2b95ca/pyrsis
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/1e/7d/ae3f0a63f41e4d2f6cb66a5b57197850f919f59e558159a4dd3a818f5082/pyseri
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/d9/6e/433a5614132576289b8643fe598dd5d51b16e130fd591564be952e15bb45/pyusb-
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/71/39/171f1c67cd00715f190ba0b100d606d440a28c93c7714febeca8b79af85e/six-1.
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/d3/91/bb331f0a43e04d950a710f402a0986a54147a35818df0e1658551c8d12e1/spinne
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/10/56/d7d66a84f96d804155f6ff2873d065368b25a07222a6fd51c4f24ef6d764/termco
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/f5/c8/d5c5dabc9b19ee7c03748f354004e5f311470cb5d1373e33670160be368b/types-
########################################################################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/64/20/cec7ce9b7c05307209542427f417d005f082771596ab0f628f6a888b8aee/qmk-1.
########################################################################################################################## 100.0%
==> Upgrading qmk/qmk/qmk
  1.1.2_4 -> 1.1.5 

==> python3 -m venv --system-site-packages --without-pip /usr/local/Cellar/qmk/1.1.5/libexec
==> python3 -m pip --python=/usr/local/Cellar/qmk/1.1.5/libexec/bin/python install /private/tmp/qmk--appdirs-20240229-27363-ia0fk
==> python3 -m pip --python=/usr/local/Cellar/qmk/1.1.5/libexec/bin/python install /private/tmp/qmk--argcomplete-20240229-27363-j
==> python3 -m pip --python=/usr/local/Cellar/qmk/1.1.5/libexec/bin/python install /private/tmp/qmk--attrs-20240229-27363-zvjrri/
==> python3 -m pip --python=/usr/local/Cellar/qmk/1.1.5/libexec/bin/python install /private/tmp/qmk--colorama-20240229-27363-pyvy
==> python3 -m pip --python=/usr/local/Cellar/qmk/1.1.5/libexec/bin/python install /private/tmp/qmk--dotty-dict-20240229-27363-wl
==> python3 -m pip --python=/usr/local/Cellar/qmk/1.1.5/libexec/bin/python install /private/tmp/qmk--halo-20240229-27363-peqr7r/h
==> python3 -m pip --python=/usr/local/Cellar/qmk/1.1.5/libexec/bin/python install /private/tmp/qmk--hid-20240229-27363-8wxeiy/hi
==> python3 -m pip --python=/usr/local/Cellar/qmk/1.1.5/libexec/bin/python install /private/tmp/qmk--hjson-20240229-27363-puv077/
==> python3 -m pip --python=/usr/local/Cellar/qmk/1.1.5/libexec/bin/python install /private/tmp/qmk--jsonschema-20240229-27363-bv
==> python3 -m pip --python=/usr/local/Cellar/qmk/1.1.5/libexec/bin/python install /private/tmp/qmk--log-symbols-20240229-27363-o
==> python3 -m pip --python=/usr/local/Cellar/qmk/1.1.5/libexec/bin/python install /private/tmp/qmk--milc-20240229-27363-kyf2dl/m
==> python3 -m pip --python=/usr/local/Cellar/qmk/1.1.5/libexec/bin/python install /private/tmp/qmk--pillow-20240229-27363-4ea1bf
Last 15 lines from /Users/adrnlow/Library/Logs/Homebrew/qmk/13.python3:
  1 error generated.
  error: command '/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Building wheel for pillow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/Cellar/qmk/1.1.5/libexec/bin/python /usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /private/tmp/tmpbs63ic0u
  cwd: /private/tmp/qmk--pillow-20240229-27363-4ea1bf/pillow-10.2.0
  Building wheel for pillow (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for pillow
Failed to build pillow
ERROR: Could not build wheels for pillow, which is required to install pyproject.toml-based projects

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/qmk/homebrew-qmk/issues

adrnlow@Adrians-MacBook-Pro-2 ~ %

**Comment by fauxpark** [comment]
Not a QMK issue; your brew install is broken.

**Comment by bbucko** [comment]
Not necessarily:

```
==> Downloading https://ghcr.io/v2/qmk/qmk/qmk/manifests/1.1.5
curl: (22) The requested URL returned error: 404

```


I'm experiencing the same problem.

**Comment by fauxpark** [comment]
OP's brew install still looks broken, but that's unrelated to the missing manifest.

**Comment by fauxpark** [comment]
I don't know what could have possibly changed between #74 and now but the bottle is no longer building. I've had to roll back the repo for the time being, sorry.

**Comment by adrnlow** [comment]
Thanks.
It appears to be an issue with the Brew install.
Finally managed to install QMK.
Much appreciate your help.
Kind regards,
adrian

Sent with [Proton Mail](https://proton.me/) secure email.
