### ISSUE TITLE
[Bug] Installation issue: 

### ISSUE THREAD

**Issue by jose-elias-alvarez** [qmk/homebrew-qmk#82]
### Describe the Bug

Running `brew install qmk/qmk/qmk` errors out at the following step:

```
==> Installing qmk/qmk/qmk
==> Pouring qmk--1.1.5_1.arm64_sonoma.bottle.tar.gz
Error: No such file or directory - /opt/homebrew/bin/qmk
```

This leaves a `qmk` executable in `$PATH`, but trying to run it throws a different error:

```
exec: Failed to execute process '/opt/homebrew/bin/qmk': The file specified the interpreter '/opt/homebrew/Cellar/qmk/1.1.5_1/libexec/bin/python', which is not an executable command.
```

`cat /opt/homebrew/bin/qmk` shows the following shebang:

```sh
#!/opt/homebrew/Cellar/qmk/1.1.5_1/libexec/bin/python
```

On my system, that's a symlink pointing at the following:

```
/opt/homebrew/Cellar/qmk/1.1.5_1/libexec/bin/python@ -> ../../../../../opt/python@3.12/Frameworks/Python.framework/Versions/3.12/bin/python3.12
```

That file doesn't exist, so I tried `brew install python@3.12` and everything works, but if that specific Python version is a dependency of the `qmk` formula, I don't know why it was missing.

### Additional Context?

I am on an M1 MacBook Pro running macOS Sequoia 15.0.1. 

I would normally assume that something is wrong with my system, but I reinstalled QMK via Homebrew a couple of weeks ago without issues, so I don't know what changed. I also spotted [this issue](https://github.com/qmk/qmk_firmware/issues/24494) on the main QMK repo, indicating that others may be having the same issue.

**Comment by fauxpark** [comment]
The `qmk` formula depends on `python`, which I guess is now pointed at `python@3.13`, however the bottle would have been built for 3.12 (hence why it can't find that installation and works after manually installing). I'll get the formula updated in a bit.

**Comment by fauxpark** [comment]
Should be fixed as of #83.

I've added the Sequoia runner to the test-bot workflow so that GHA can build and publish bottles for it, but the AVR and ARM toolchains over on osx-cross need to be bottled for Sequoia first for that to work. For the moment Brew should simply download the Sonoma bottle instead and that'll work just fine.

**Comment by sushilbansal** [comment]
the issue seems to be back. getting the same error.

**Comment by 869mb9mf5h-wq** [comment]
> the issue seems to be back. getting the same error.

Same here

**Comment by dmitriyKononenko** [comment]
Had the same issue. This was resolved in my case this way:

1. Run: `readlink /opt/homebrew/Cellar/qmk/1.1.8/libexec/bin/python`
2. This returns something like: `python3.13`
3. Install the required python version: `brew install python@3.13`
